导入需要的库

In [1]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier

读取csv中的数据

In [2]:
df = pd.read_csv('train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

检查包含空值的数据列

In [3]:
df.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

先处理Age列的空值，这里用年龄均值填充Nan数据

In [4]:
df['Age'].fillna(df['Age'].mean(), inplace=True)
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket     Fare Cabin Embarked  
0        1      0         A/5 21171   7.2500   NaN        S  
1        1      0          PC 17599  71.2833   C85        C  
2        0      0  STON/O2. 3101282   7.9250   NaN        S  
3        1      0            113803  53.1000  C123        S  
4        0      0            373450   8.0500   NaN        S  
..     ...    ...               ...      ...   ...      ...  
886      0      0            211536  13.0000   NaN        S  
887      0      0            112053  30.0000   B42        S  
888      1      2        W./C. 6607  23.4500   NaN        S  
889      0      0            111369  30.0000  C148        C  
890      0      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

接下来处理Embarked列的数据，作为登船港口的数据，这里用众数取代Nan值

In [5]:
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket     Fare Cabin Embarked  
0        1      0         A/5 21171   7.2500   NaN        S  
1        1      0          PC 17599  71.2833   C85        C  
2        0      0  STON/O2. 3101282   7.9250   NaN        S  
3        1      0            113803  53.1000  C123        S  
4        0      0            373450   8.0500   NaN        S  
..     ...    ...               ...      ...   ...      ...  
886      0      0            211536  13.0000   NaN        S  
887      0      0            112053  30.0000   B42        S  
888      1      2        W./C. 6607  23.4500   NaN        S  
889      0      0            111369  30.0000  C148        C  
890      0      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

检查是否有空数据

In [6]:
df.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked       False
dtype: bool

为了训练方便，把Sex和Embarked的值以数值替代

In [13]:
df.loc[df['Embarked'] == 'S', 'Embarked'] = 0
df.loc[df['Embarked'] == 'C', 'Embarked'] = 1
df.loc[df['Embarked'] == 'Q', 'Embarked'] = 2
df.loc[df['Sex'] == 'male', 'Sex'] = 1
df.loc[df['Sex'] == 'female', 'Sex'] = 2
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name Sex        Age  SibSp  \
0                              Braund, Mr. Owen Harris   1  22.000000      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   2  38.000000      1   
2                               Heikkinen, Miss. Laina   2  26.000000      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)   2  35.000000      1   
4                             Allen, Mr. William Henry   1  35.000000      0   
..                                                 ...  ..        ...    ...   
886                              Montvila, Rev. Juozas   1  27.000000      0   
887                       Graham, Miss. Margaret Edith   2  19.000000      0   
888           Johnston, Miss. Catherine Helen "Carrie"   2  29.699118      1   
889                              Behr, Mr. Karl Howell   1  26.000000      0   
890                                Dooley, Mr. Patrick   1  32.000000      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        0  
1        0          PC 17599  71.2833   C85        1  
2        0  STON/O2. 3101282   7.9250   NaN        0  
3        0            113803  53.1000  C123        0  
4        0            373450   8.0500   NaN        0  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        0  
887      0            112053  30.0000   B42        0  
888      2        W./C. 6607  23.4500   NaN        0  
889      0            111369  30.0000  C148        1  
890      0            370376   7.7500   NaN        2  

[891 rows x 12 columns]

把数据填入list做进一步处理

In [8]:
df_list = []
df_list.append(df)

筛选可以用于训练的数据，并整合到数组中作为训练的输入和输出

In [14]:
input_cols = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
output_col = 'Survived'

x_tr = []
y_tr = []

for data in df_list:
    x_tr.append(data[input_cols].values)
    y_tr.append(data[output_col].values)
x_train = np.concatenate(x_tr, axis=0)
y_train = np.concatenate(y_tr)
print(x_train)
print(y_train)

[[3 1 22.0 ... 0 7.25 0]
 [1 2 38.0 ... 0 71.2833 1]
 [3 2 26.0 ... 0 7.925 0]
 ...
 [3 2 29.69911764705882 ... 2 23.45 0]
 [1 1 26.0 ... 0 30.0 1]
 [3 1 32.0 ... 0 7.75 2]]
[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 

构建mlp模型并训练

In [15]:
mlp = MLPClassifier(hidden_layer_sizes=64, alpha=0, max_iter=200, random_state=42, learning_rate_init=1e-3)
mlp.fit(x_train, y_train)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(alpha=0, hidden_layer_sizes=64, random_state=42)

导入测试数据集

In [16]:
test_df = pd.read_csv('test.csv')
test_df

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [25]:
test_df.isnull().any()

PassengerId    False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare            True
Cabin           True
Embarked       False
dtype: bool

In [27]:
test_df['Age'].fillna(test_df['Age'].mean(), inplace=True)
test_df['Fare'].fillna(test_df['Fare'].mode()[0], inplace=True)
test_df.isnull().any()

PassengerId    False
Pclass         False
Name           False
Sex            False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked       False
dtype: bool

用数值代替Sex和Embarked

In [28]:
test_df.loc[test_df['Embarked'] == 'S', 'Embarked'] = 0
test_df.loc[test_df['Embarked'] == 'C', 'Embarked'] = 1
test_df.loc[test_df['Embarked'] == 'Q', 'Embarked'] = 2
test_df.loc[test_df['Sex'] == 'male', 'Sex'] = 1
test_df.loc[test_df['Sex'] == 'female', 'Sex'] = 2
test_df

PassengerId  Pclass                                          Name Sex  \
0            892       3                              Kelly, Mr. James   1   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   2   
2            894       2                     Myles, Mr. Thomas Francis   1   
3            895       3                              Wirz, Mr. Albert   1   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   2   
..           ...     ...                                           ...  ..   
413         1305       3                            Spector, Mr. Woolf   1   
414         1306       1                  Oliva y Ocana, Dona. Fermina   2   
415         1307       3                  Saether, Mr. Simon Sivertsen   1   
416         1308       3                           Ware, Mr. Frederick   1   
417         1309       3                      Peter, Master. Michael J   1   

          Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0    34.50000      0      0              330911    7.8292   NaN        2  
1    47.00000      1      0              363272    7.0000   NaN        0  
2    62.00000      0      0              240276    9.6875   NaN        2  
3    27.00000      0      0              315154    8.6625   NaN        0  
4    22.00000      1      1             3101298   12.2875   NaN        0  
..        ...    ...    ...                 ...       ...   ...      ...  
413  30.27259      0      0           A.5. 3236    8.0500   NaN        0  
414  39.00000      0      0            PC 17758  108.9000  C105        1  
415  38.50000      0      0  SOTON/O.Q. 3101262    7.2500   NaN        0  
416  30.27259      0      0              359309    8.0500   NaN        0  
417  30.27259      1      1                2668   22.3583   NaN        1  

[418 rows x 11 columns]

In [29]:
test_list = []
test_list.append(test_df)

# 筛选用于训练的数据列
test_input_cols = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

x_test = []

for data in test_list:
    x_test.append(data[test_input_cols].values)

x_test_set = np.concatenate(x_test, axis=0)
x_test_set.shape

(418, 7)

In [30]:
result = mlp.predict(x_test_set)
result

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,

In [31]:
test_df['Survived'] = result
test_df

PassengerId  Pclass                                          Name Sex  \
0            892       3                              Kelly, Mr. James   1   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   2   
2            894       2                     Myles, Mr. Thomas Francis   1   
3            895       3                              Wirz, Mr. Albert   1   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   2   
..           ...     ...                                           ...  ..   
413         1305       3                            Spector, Mr. Woolf   1   
414         1306       1                  Oliva y Ocana, Dona. Fermina   2   
415         1307       3                  Saether, Mr. Simon Sivertsen   1   
416         1308       3                           Ware, Mr. Frederick   1   
417         1309       3                      Peter, Master. Michael J   1   

          Age  SibSp  Parch              Ticket      Fare Cabin Embarked  \
0    34.50000      0      0              330911    7.8292   NaN        2   
1    47.00000      1      0              363272    7.0000   NaN        0   
2    62.00000      0      0              240276    9.6875   NaN        2   
3    27.00000      0      0              315154    8.6625   NaN        0   
4    22.00000      1      1             3101298   12.2875   NaN        0   
..        ...    ...    ...                 ...       ...   ...      ...   
413  30.27259      0      0           A.5. 3236    8.0500   NaN        0   
414  39.00000      0      0            PC 17758  108.9000  C105        1   
415  38.50000      0      0  SOTON/O.Q. 3101262    7.2500   NaN        0   
416  30.27259      0      0              359309    8.0500   NaN        0   
417  30.27259      1      1                2668   22.3583   NaN        1   

     Survived  
0           0  
1           0  
2           0  
3           0  
4           1  
..        ...  
413         0  
414         1  
415         0  
416         0  
417         0  

[418 rows x 12 columns]

导出csv

In [39]:
test_df.to_csv(path_or_buf='predict_result.csv', columns=['PassengerId', 'Survived'], index=False)